# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-07-10 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000000)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=10000)),
                ('district', models.CharField(max_length=10000)),
                ('state', models.CharField(max_length=100000)),
                ('pincode', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DistributorFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('distributor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('model_no', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=10000)),
                ('active_passive', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PASSIVE', 'PASSIVE')], default='ACTIVE', max_length=50)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('pdf1', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('pdf2', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('website_url', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Subgroup1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('active_passive', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PASSIVE', 'PASSIVE')], default='ACTIVE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subgroup2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('subgroup1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Subgroup1')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subgroup1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Subgroup1'),
        ),
        migrations.AddField(
            model_name='product',
            name='subgroup2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Subgroup2'),
        ),
    ]
